/*
 * Synapse — The intelligence layer for AI workflows
 * Copyright (c) 2026 Daniel De Vecchi
 *
 * Licensed under AGPL-3.0-or-later.
 * See LICENSE for details.
 *
 * Commercial license: daniel@pixarts.eu
 */

import { getConnectorEnv, type ConnectorCtx } from './index.js'

const GH_API = 'https://api.github.com'

async function ghFetch(
  path: string,
  token: string,
  opts: RequestInit = {},
): Promise<Response> {
  const res = await fetch(`${GH_API}${path}`, {
    ...opts,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...(opts.headers ?? {}),
    },
  })
  return res
}

export interface GithubPrResult {
  prUrl: string
  prNumber: number
  branch: string
  filesCommitted: string[]
}

export async function createGithubPr(
  params: {
    repo: string         // "owner/repo"
    convTitle: string
    artifactHtml: string
    baseBranch?: string  // default: "main"
  },
  ctx: ConnectorCtx,
): Promise<GithubPrResult> {
  const token = getConnectorEnv('GITHUB_TOKEN', ctx)
  const base = params.baseBranch ?? 'main'

  // 1. Get base branch SHA
  const refRes = await ghFetch(`/repos/${params.repo}/git/refs/heads/${base}`, token)
  if (!refRes.ok) {
    const err = await refRes.json().catch(() => ({})) as Record<string, unknown>
    throw new Error(`GitHub: cannot read base branch "${base}" on ${params.repo}: ${(err as Record<string, unknown>)['message'] ?? refRes.status}`)
  }
  const refData = await refRes.json() as { object: { sha: string } }
  const baseSha = refData.object.sha

  // 2. Create new branch
  const slug = params.convTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40)
  const date = new Date().toISOString().slice(0, 10)
  const branch = `studio/${slug}-${date}`

  const branchRes = await ghFetch(`/repos/${params.repo}/git/refs`, token, {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
  })
  if (!branchRes.ok && branchRes.status !== 422) {
    // 422 = branch already exists — continue anyway
    throw new Error(`GitHub: cannot create branch "${branch}": ${branchRes.status}`)
  }

  // 3. Commit artifact.html to new branch
  const filePath = `studio-preview/${slug}.html`
  const content = Buffer.from(params.artifactHtml, 'utf-8').toString('base64')

  // Check if file exists (to get its SHA for update)
  let existingSha: string | undefined
  const fileCheck = await ghFetch(
    `/repos/${params.repo}/contents/${filePath}?ref=${branch}`,
    token,
  )
  if (fileCheck.ok) {
    const fileData = await fileCheck.json() as { sha: string }
    existingSha = fileData.sha
  }

  const commitBody: Record<string, unknown> = {
    message: `feat(studio): ${params.convTitle} — Studio export`,
    content,
    branch,
  }
  if (existingSha) commitBody.sha = existingSha

  const commitRes = await ghFetch(
    `/repos/${params.repo}/contents/${filePath}`,
    token,
    { method: 'PUT', body: JSON.stringify(commitBody) },
  )
  if (!commitRes.ok) {
    throw new Error(`GitHub: cannot commit file: ${commitRes.status}`)
  }

  // 4. Create PR
  const prRes = await ghFetch(`/repos/${params.repo}/pulls`, token, {
    method: 'POST',
    body: JSON.stringify({
      title: `[Studio] ${params.convTitle}`,
      body: `Generated by Studio.\n\nPreview file: \`${filePath}\`\n\n---\n*Auto-generated — do not merge without review.*`,
      head: branch,
      base,
      draft: true,
    }),
  })
  if (!prRes.ok) {
    const errData = await prRes.json().catch(() => ({})) as Record<string, unknown>
    throw new Error(`GitHub: cannot create PR: ${errData['message'] ?? prRes.status}`)
  }
  const pr = await prRes.json() as { html_url: string; number: number }

  return {
    prUrl: pr.html_url,
    prNumber: pr.number,
    branch,
    filesCommitted: [filePath],
  }
}
