-- 5 VISUAL DIRECTIONS
INSERT OR IGNORE INTO studio_directions (id, name, description, moodboard_json) VALUES
('dir-editorial',    'Editorial',      'Magazine-grade typography, generous whitespace, strong hierarchy. Black/white with one accent. Inspired by NYT, Monocle, The Verge.', '[]'),
('dir-minimal',      'Modern Minimal', 'Invisible UI. Everything earns its place. Neutral palette, precise spacing, no decoration. Inspired by Linear, Vercel, Stripe.', '[]'),
('dir-tech-utility', 'Tech Utility',   'Function-first. Dense information, monospace accents, dark mode default. Inspired by GitHub, Datadog, Sentry, terminal UIs.', '[]'),
('dir-brutalist',    'Brutalist',      'Raw structure exposed. Stark contrast, no rounding, bold borders, unexpected layout. Inspired by Brutalist Websites, Bloomberg.', '[]'),
('dir-soft-warm',    'Soft Warm',      'Approachable, friendly, rounded. Warm neutrals, soft shadows, pastel accents. Inspired by Notion, Loom, Intercom.', '[]');

-- 31 SKILLS
INSERT OR IGNORE INTO studio_skills (id, name, description, category) VALUES
('sk-web-prototype',  'web-prototype',      'Interactive HTML prototype for any web surface', 'web'),
('sk-saas-landing',   'saas-landing',       'SaaS product landing page with hero, features, pricing', 'marketing'),
('sk-dashboard',      'dashboard',          'Admin or analytics dashboard with charts and tables', 'app'),
('sk-mobile-app',     'mobile-app',         'Mobile app screen or flow (375px viewport)', 'mobile'),
('sk-email-template', 'email-template',     'HTML email template (600px, inbox-safe CSS)', 'email'),
('sk-blog-post',      'blog-post',          'Long-form article layout with TOC and typography', 'content'),
('sk-ecommerce',      'e-commerce',         'Product page, collection grid, or checkout flow', 'commerce'),
('sk-portfolio',      'portfolio',          'Personal or agency portfolio showcase', 'marketing'),
('sk-docs-site',      'docs-site',          'Technical documentation with sidebar nav and code blocks', 'content'),
('sk-admin-panel',    'admin-panel',        'Back-office management interface with CRUD tables', 'app'),
('sk-marketing-site', 'marketing-site',     'Multi-section marketing site (hero + social proof + CTA)', 'marketing'),
('sk-pricing-page',   'pricing-page',       'Pricing tiers comparison page with toggle and FAQ', 'marketing'),
('sk-checkout-flow',  'checkout-flow',      'Multi-step checkout: cart → shipping → payment → confirm', 'commerce'),
('sk-onboarding',     'onboarding',         'User onboarding wizard or empty-state first-run flow', 'app'),
('sk-login-signup',   'login-signup',       'Auth screens: login, signup, password reset, MFA', 'app'),
('sk-dataviz',        'data-visualization', 'Charts, graphs, dashboards powered by real-looking data', 'app'),
('sk-kanban',         'kanban-board',       'Drag-and-drop kanban board with columns and cards', 'app'),
('sk-calendar',       'calendar-ui',        'Month/week calendar view with events and sidebar', 'app'),
('sk-chat',           'chat-interface',     'Real-time chat UI with threads, reactions, presence', 'app'),
('sk-form-builder',   'form-builder',       'Dynamic form with validation, multi-step, conditional', 'app'),
('sk-video-player',   'video-player',       'Custom video player with controls and chapter markers', 'media'),
('sk-map',            'map-interface',      'Interactive map with pins, filters, and detail panel', 'app'),
('sk-timeline',       'timeline',           'Vertical or horizontal timeline for history or roadmap', 'content'),
('sk-gallery',        'gallery',            'Masonry or grid image gallery with lightbox', 'media'),
('sk-profile-page',   'profile-page',       'User or company profile with bio, stats, activity feed', 'app'),
('sk-settings-page',  'settings-page',      'Settings panel with sections, toggles, and danger zone', 'app'),
('sk-search-results', 'search-results',     'Search results page with filters, facets, and pagination', 'app'),
('sk-notifications',  'notifications',      'Notification center with grouping, mark-read, actions', 'app'),
('sk-table-view',     'table-view',         'Data table with sorting, filtering, inline edit, export', 'app'),
('sk-wizard',         'wizard-flow',        'Multi-step wizard with progress bar and validation', 'app'),
('sk-card-grid',      'card-grid',          'Responsive card grid for content, products, or people', 'web');

-- 72 DESIGN SYSTEMS
-- SaaS / Productivity (20)
INSERT OR IGNORE INTO studio_design_systems (id, name, category, source_url, tokens_json) VALUES
('ds-linear',      'Linear',         'saas',     'https://linear.app',              '{"primary":"#5E6AD2","bg":"#0F0F10","surface":"#1A1A1C","text":"#E2E2E2","radius":"4px"}'),
('ds-notion',      'Notion',         'saas',     'https://notion.so',               '{"primary":"#000000","bg":"#FFFFFF","surface":"#F7F6F3","text":"#37352F","radius":"3px"}'),
('ds-vercel',      'Vercel',         'devtools', 'https://vercel.com',              '{"primary":"#000000","bg":"#000000","surface":"#111111","text":"#EDEDED","radius":"6px"}'),
('ds-supabase',    'Supabase',       'devtools', 'https://supabase.com',            '{"primary":"#3ECF8E","bg":"#1C1C1C","surface":"#2A2A2A","text":"#EDEDED","radius":"6px"}'),
('ds-railway',     'Railway',        'devtools', 'https://railway.app',             '{"primary":"#8B5CF6","bg":"#131415","surface":"#1E1E1E","text":"#EDEDED","radius":"8px"}'),
('ds-render',      'Render',         'devtools', 'https://render.com',              '{"primary":"#46E3B7","bg":"#002B36","surface":"#073642","text":"#FDF6E3","radius":"6px"}'),
('ds-fly',         'Fly.io',         'devtools', 'https://fly.io',                  '{"primary":"#7C3AED","bg":"#0F172A","surface":"#1E293B","text":"#F1F5F9","radius":"6px"}'),
('ds-retool',      'Retool',         'saas',     'https://retool.com',              '{"primary":"#3D5AFE","bg":"#FFFFFF","surface":"#F5F5F5","text":"#1A1A1A","radius":"4px"}'),
('ds-airtable',    'Airtable',       'saas',     'https://airtable.com',            '{"primary":"#2D7FF9","bg":"#FFFFFF","surface":"#F5F5F5","text":"#111827","radius":"6px"}'),
('ds-coda',        'Coda',           'saas',     'https://coda.io',                 '{"primary":"#F46A54","bg":"#FFFFFF","surface":"#F9F9F9","text":"#1B1B1B","radius":"4px"}'),
('ds-clickup',     'ClickUp',        'saas',     'https://clickup.com',             '{"primary":"#7B68EE","bg":"#FFFFFF","surface":"#F5F5F5","text":"#1B1B1B","radius":"6px"}'),
('ds-asana',       'Asana',          'saas',     'https://asana.com',               '{"primary":"#F06A6A","bg":"#FFFFFF","surface":"#F9F9F9","text":"#1E1F21","radius":"6px"}'),
('ds-todoist',     'Todoist',        'saas',     'https://todoist.com',             '{"primary":"#DB4035","bg":"#FFFFFF","surface":"#F5F5F5","text":"#202020","radius":"5px"}'),
('ds-obsidian',    'Obsidian',       'saas',     'https://obsidian.md',             '{"primary":"#7C5CBF","bg":"#1E1E1E","surface":"#252526","text":"#DCDDDE","radius":"4px"}'),
('ds-loom',        'Loom',           'saas',     'https://loom.com',                '{"primary":"#625DF5","bg":"#FFFFFF","surface":"#F5F4FF","text":"#1A1523","radius":"8px"}'),
('ds-miro',        'Miro',           'saas',     'https://miro.com',                '{"primary":"#FFD02F","bg":"#1A1A1A","surface":"#2E2E2E","text":"#FFFFFF","radius":"6px"}'),
('ds-figma',       'Figma',          'design',   'https://figma.com',               '{"primary":"#1ABCFE","bg":"#1E1E1E","surface":"#2C2C2C","text":"#FFFFFF","radius":"2px"}'),
('ds-framer',      'Framer',         'design',   'https://framer.com',              '{"primary":"#0055FF","bg":"#0A0A0A","surface":"#111111","text":"#FFFFFF","radius":"8px"}'),
('ds-planetscale', 'PlanetScale',    'devtools', 'https://planetscale.com',         '{"primary":"#F400A1","bg":"#0F0F0F","surface":"#1A1A1A","text":"#EDEDED","radius":"6px"}'),
('ds-intercom',    'Intercom',       'saas',     'https://intercom.com',            '{"primary":"#286EFA","bg":"#FFFFFF","surface":"#F3F4F6","text":"#1F1F1F","radius":"6px"}'),
-- Dev Tools (10)
('ds-github',      'GitHub',         'devtools', 'https://github.com',              '{"primary":"#2DA44E","bg":"#0D1117","surface":"#161B22","text":"#E6EDF3","radius":"6px"}'),
('ds-gitlab',      'GitLab',         'devtools', 'https://gitlab.com',              '{"primary":"#FC6D26","bg":"#FFFFFF","surface":"#F5F5F5","text":"#303030","radius":"4px"}'),
('ds-sourcegraph', 'Sourcegraph',    'devtools', 'https://sourcegraph.com',         '{"primary":"#A112FF","bg":"#0F111A","surface":"#1C2030","text":"#E6EEF8","radius":"4px"}'),
('ds-sentry',      'Sentry',         'devtools', 'https://sentry.io',               '{"primary":"#6559C5","bg":"#0D0A1F","surface":"#1A1625","text":"#EBE6FF","radius":"6px"}'),
('ds-datadog',     'Datadog',        'devtools', 'https://datadoghq.com',           '{"primary":"#774AA4","bg":"#FFFFFF","surface":"#F5F5F5","text":"#1A1A1A","radius":"4px"}'),
('ds-posthog',     'PostHog',        'devtools', 'https://posthog.com',             '{"primary":"#F54E00","bg":"#1D1D1D","surface":"#2C2C2C","text":"#EEEFE9","radius":"4px"}'),
('ds-segment',     'Segment',        'devtools', 'https://segment.com',             '{"primary":"#52BD94","bg":"#FFFFFF","surface":"#F5F5F5","text":"#1F1F1F","radius":"6px"}'),
('ds-mixpanel',    'Mixpanel',       'devtools', 'https://mixpanel.com',            '{"primary":"#7856FF","bg":"#FFFFFF","surface":"#F5F5F5","text":"#1F1F1F","radius":"6px"}'),
('ds-launchdarkly','LaunchDarkly',   'devtools', 'https://launchdarkly.com',        '{"primary":"#405BFF","bg":"#FFFFFF","surface":"#F5F5F5","text":"#1F1F1F","radius":"6px"}'),
('ds-vercelai',    'Vercel AI SDK',  'devtools', 'https://sdk.vercel.ai',           '{"primary":"#FFFFFF","bg":"#000000","surface":"#111111","text":"#EDEDED","radius":"4px"}'),
-- UI Libraries / Design Systems (15)
('ds-tailwind',    'Tailwind CSS',         'ui-lib', 'https://tailwindcss.com',             '{"primary":"#06B6D4","bg":"#FFFFFF","surface":"#F8FAFC","text":"#0F172A","radius":"6px"}'),
('ds-shadcn',      'shadcn/ui',            'ui-lib', 'https://ui.shadcn.com',               '{"primary":"#18181B","bg":"#FFFFFF","surface":"#F4F4F5","text":"#09090B","radius":"6px"}'),
('ds-radix',       'Radix UI',             'ui-lib', 'https://radix-ui.com',                '{"primary":"#0090FF","bg":"#FFFFFF","surface":"#F8F8F8","text":"#11181C","radius":"4px"}'),
('ds-material3',   'Material Design 3',    'ui-lib', 'https://m3.material.io',              '{"primary":"#6750A4","bg":"#FFFBFE","surface":"#FEF7FF","text":"#1C1B1F","radius":"16px"}'),
('ds-antd',        'Ant Design',           'ui-lib', 'https://ant.design',                  '{"primary":"#1677FF","bg":"#FFFFFF","surface":"#F5F5F5","text":"#000000","radius":"6px"}'),
('ds-chakra',      'Chakra UI',            'ui-lib', 'https://chakra-ui.com',               '{"primary":"#319795","bg":"#FFFFFF","surface":"#F7FAFC","text":"#1A202C","radius":"6px"}'),
('ds-carbon',      'IBM Carbon',           'ui-lib', 'https://carbondesignsystem.com',      '{"primary":"#0F62FE","bg":"#161616","surface":"#262626","text":"#F4F4F4","radius":"0px"}'),
('ds-lightning',   'Salesforce Lightning', 'ui-lib', 'https://lightningdesignsystem.com',   '{"primary":"#0070D2","bg":"#FFFFFF","surface":"#F3F3F3","text":"#16325C","radius":"4px"}'),
('ds-spectrum',    'Adobe Spectrum',       'ui-lib', 'https://spectrum.adobe.com',          '{"primary":"#378EF0","bg":"#1F1F1F","surface":"#2C2C2C","text":"#EBEBEB","radius":"4px"}'),
('ds-atlassian',   'Atlassian',            'ui-lib', 'https://atlassian.design',            '{"primary":"#0052CC","bg":"#FFFFFF","surface":"#F4F5F7","text":"#172B4D","radius":"3px"}'),
('ds-polaris',     'Shopify Polaris',      'ui-lib', 'https://polaris.shopify.com',         '{"primary":"#008060","bg":"#FFFFFF","surface":"#F6F6F7","text":"#202223","radius":"8px"}'),
('ds-fluent',      'Microsoft Fluent',     'ui-lib', 'https://fluent2.microsoft.design',    '{"primary":"#0078D4","bg":"#FFFFFF","surface":"#F3F3F3","text":"#201F1E","radius":"4px"}'),
('ds-apple-hig',   'Apple HIG',            'ui-lib', 'https://developer.apple.com/design',  '{"primary":"#007AFF","bg":"#FFFFFF","surface":"#F2F2F7","text":"#000000","radius":"10px"}'),
('ds-primer',      'GitHub Primer',        'ui-lib', 'https://primer.style',                '{"primary":"#0969DA","bg":"#FFFFFF","surface":"#F6F8FA","text":"#24292F","radius":"6px"}'),
('ds-bootstrap',   'Bootstrap',            'ui-lib', 'https://getbootstrap.com',            '{"primary":"#712CF9","bg":"#FFFFFF","surface":"#F8F9FA","text":"#212529","radius":"4px"}'),
-- Consumer (12)
('ds-stripe',      'Stripe',     'fintech',  'https://stripe.com',      '{"primary":"#635BFF","bg":"#FFFFFF","surface":"#F6F9FC","text":"#0A2540","radius":"4px"}'),
('ds-airbnb',      'Airbnb',     'consumer', 'https://airbnb.com',      '{"primary":"#FF385C","bg":"#FFFFFF","surface":"#F7F7F7","text":"#222222","radius":"8px"}'),
('ds-uber',        'Uber',       'consumer', 'https://uber.com',        '{"primary":"#000000","bg":"#FFFFFF","surface":"#F6F6F6","text":"#000000","radius":"4px"}'),
('ds-spotify',     'Spotify',    'consumer', 'https://spotify.com',     '{"primary":"#1DB954","bg":"#121212","surface":"#282828","text":"#FFFFFF","radius":"4px"}'),
('ds-discord',     'Discord',    'consumer', 'https://discord.com',     '{"primary":"#5865F2","bg":"#313338","surface":"#2B2D31","text":"#DBDEE1","radius":"8px"}'),
('ds-slack',       'Slack',      'consumer', 'https://slack.com',       '{"primary":"#4A154B","bg":"#FFFFFF","surface":"#F8F8F8","text":"#1D1C1D","radius":"4px"}'),
('ds-zoom',        'Zoom',       'consumer', 'https://zoom.us',         '{"primary":"#0B5CFF","bg":"#FFFFFF","surface":"#F5F5F5","text":"#232333","radius":"8px"}'),
('ds-twitter',     'X / Twitter','consumer', 'https://x.com',           '{"primary":"#1D9BF0","bg":"#000000","surface":"#16181C","text":"#E7E9EA","radius":"9999px"}'),
('ds-instagram',   'Instagram',  'consumer', 'https://instagram.com',   '{"primary":"#E1306C","bg":"#FAFAFA","surface":"#FFFFFF","text":"#262626","radius":"8px"}'),
('ds-pinterest',   'Pinterest',  'consumer', 'https://pinterest.com',   '{"primary":"#E60023","bg":"#FFFFFF","surface":"#F0F0F0","text":"#111111","radius":"16px"}'),
('ds-dribbble',    'Dribbble',   'design',   'https://dribbble.com',    '{"primary":"#EA4C89","bg":"#FFFFFF","surface":"#F5F5F5","text":"#0D0D0D","radius":"6px"}'),
('ds-behance',     'Behance',    'design',   'https://behance.net',     '{"primary":"#0057FF","bg":"#FFFFFF","surface":"#F5F5F5","text":"#1B1B1B","radius":"4px"}'),
-- E-commerce (8)
('ds-shopify',     'Shopify',     'ecommerce', 'https://shopify.com',     '{"primary":"#008060","bg":"#FFFFFF","surface":"#F6F6F7","text":"#202223","radius":"4px"}'),
('ds-woocommerce', 'WooCommerce', 'ecommerce', 'https://woocommerce.com', '{"primary":"#96588A","bg":"#FFFFFF","surface":"#F1F1F1","text":"#3D3D3D","radius":"4px"}'),
('ds-etsy',        'Etsy',        'ecommerce', 'https://etsy.com',        '{"primary":"#F1641E","bg":"#FFFFFF","surface":"#F5F5F5","text":"#222222","radius":"2px"}'),
('ds-amazon',      'Amazon',      'ecommerce', 'https://amazon.com',      '{"primary":"#FF9900","bg":"#FFFFFF","surface":"#EAEDED","text":"#0F1111","radius":"4px"}'),
('ds-ebay',        'eBay',        'ecommerce', 'https://ebay.com',        '{"primary":"#E53238","bg":"#FFFFFF","surface":"#F5F5F5","text":"#191919","radius":"4px"}'),
('ds-ikea',        'IKEA',        'ecommerce', 'https://ikea.com',        '{"primary":"#003399","bg":"#FFDA1A","surface":"#FFFFFF","text":"#111111","radius":"0px"}'),
('ds-bigcommerce', 'BigCommerce', 'ecommerce', 'https://bigcommerce.com', '{"primary":"#34313F","bg":"#FFFFFF","surface":"#F5F5F5","text":"#34313F","radius":"4px"}'),
('ds-wix',         'Wix',         'ecommerce', 'https://wix.com',         '{"primary":"#116DFF","bg":"#FFFFFF","surface":"#F5F5F5","text":"#162D3D","radius":"4px"}'),
-- Finance (7)
('ds-revolut',   'Revolut',   'fintech', 'https://revolut.com',   '{"primary":"#0075EB","bg":"#000000","surface":"#1A1A1A","text":"#FFFFFF","radius":"8px"}'),
('ds-wise',      'Wise',      'fintech', 'https://wise.com',      '{"primary":"#9FE870","bg":"#FFFFFF","surface":"#F5F5F5","text":"#163300","radius":"8px"}'),
('ds-monzo',     'Monzo',     'fintech', 'https://monzo.com',     '{"primary":"#FF4F64","bg":"#FFFFFF","surface":"#F9F9F9","text":"#18191A","radius":"8px"}'),
('ds-coinbase',  'Coinbase',  'fintech', 'https://coinbase.com',  '{"primary":"#1652F0","bg":"#FFFFFF","surface":"#F5F5F5","text":"#0A0B0D","radius":"8px"}'),
('ds-robinhood', 'Robinhood', 'fintech', 'https://robinhood.com', '{"primary":"#00C805","bg":"#FFFFFF","surface":"#F5F5F5","text":"#000000","radius":"8px"}'),
('ds-bloomberg', 'Bloomberg', 'fintech', 'https://bloomberg.com', '{"primary":"#FF8000","bg":"#000000","surface":"#1A1A1A","text":"#FFFFFF","radius":"0px"}'),
('ds-n26',       'N26',       'fintech', 'https://n26.com',       '{"primary":"#38C172","bg":"#FFFFFF","surface":"#F5F5F5","text":"#1A1A1A","radius":"8px"}');

-- 93 MEDIA PROMPT TEMPLATES
-- Image / GPT Image-2 (40)
INSERT OR IGNORE INTO studio_media_templates (id, name, type, category, prompt_template) VALUES
('mt-img-hero',         'Product Hero',           'image', 'image', 'Clean product hero image: {{product}} on minimal {{color}} background. Studio lighting, 4K, no text, professional.'),
('mt-img-feature',      'Feature Highlight',      'image', 'image', 'Feature illustration: {{feature_name}} concept. Flat design, {{brand_color}} palette, isometric, clean.'),
('mt-img-social-proof', 'Social Proof Banner',    'image', 'image', 'Trust badge / social proof graphic: {{metric}} in bold typography. {{brand}} color scheme, minimal, no faces.'),
('mt-img-mockup',       'App Mockup',             'image', 'image', 'Device mockup: {{device}} showing {{app_type}} UI. {{color}} background, studio quality, shadows.'),
('mt-img-icon-set',     'Icon Set',               'image', 'image', 'Icon set of 6: {{theme}} icons. Flat, 2px stroke, {{color}}, consistent style, white background.'),
('mt-img-texture',      'Background Texture',     'image', 'image', 'Abstract background texture: {{style}} pattern, {{color_palette}}, 4K, tileable, no text.'),
('mt-img-blog-header',  'Blog Header',            'image', 'image', 'Blog post header: {{topic}} theme. {{mood}} atmosphere, wide 16:9, typography placeholder space left.'),
('mt-img-newsletter',   'Newsletter Header',      'image', 'image', 'Email newsletter header: {{brand}} style, {{color}} accent, 600px wide composition, professional.'),
('mt-img-social-post',  'Social Media Post',      'image', 'image', 'Social post 1:1: {{message}} concept, {{brand_color}}, bold, thumb-stopping, no lorem ipsum text.'),
('mt-img-infographic',  'Infographic',            'image', 'image', 'Infographic: {{topic}} with {{stat_count}} stats. Clean, {{color}} accent, icon-driven, white background.'),
('mt-img-team',         'Team / People',          'image', 'image', 'Abstract team illustration: {{team_size}} diverse silhouettes. {{style}}, {{color_palette}}, no faces.'),
('mt-img-case-study',   'Case Study Visual',      'image', 'image', 'Case study cover: {{client}} project. Before/after split, professional, {{color}} brand, results-focused.'),
('mt-img-cta-banner',   'CTA Banner',             'image', 'image', 'Call-to-action banner: {{action}} message space. {{color}} gradient, bold, urgent, 1200x400px.'),
('mt-img-pricing-bg',   'Pricing Background',     'image', 'image', 'Pricing section background: {{style}} pattern, {{color}} tones, subtle, no text, web-ready.'),
('mt-img-404',          '404 / Error Page',       'image', 'image', 'Error page illustration: 404 or lost concept. {{style}}, {{color}}, friendly, no harsh emotions.'),
('mt-img-empty-state',  'Empty State',            'image', 'image', 'Empty state illustration: {{context}} (no data/results). {{style}}, {{color}}, optimistic, simple.'),
('mt-img-onboarding',   'Onboarding Illustration','image', 'image', 'Onboarding step illustration: {{step_concept}}. {{style}}, {{color_palette}}, friendly, instructional.'),
('mt-img-logo-bg',      'Logo Background',        'image', 'image', 'Branded background for {{logo_color}} logo. Complementary {{style}} pattern, web-ready, 1920x1080.'),
('mt-img-og-image',     'OG / Social Card',       'image', 'image', 'Open Graph image: {{title}} and {{brand}}. 1200x630px, bold typography space, {{color}} background.'),
('mt-img-dark-hero',    'Dark Mode Hero',         'image', 'image', 'Dark mode hero: {{product}} on dark {{color}} background. Glow effects, premium, 4K.'),
('mt-img-split-screen', 'Split Screen',           'image', 'image', 'Split screen: before {{before}} / after {{after}}. 50/50, clean divider, professional contrast.'),
('mt-img-gradient-bg',  'Gradient Background',    'image', 'image', 'Gradient mesh background: {{color1}} to {{color2}}. Smooth, modern, web-safe, 4K, no grain.'),
('mt-img-dashboard-ss', 'Dashboard Screenshot',   'image', 'image', 'Stylized dashboard screenshot: {{data_type}} analytics. Dark UI, glowing charts, premium feel.'),
('mt-img-mobile-hero',  'Mobile Hero',            'image', 'image', 'Mobile app hero: {{app_name}} on iPhone/Android. {{color}} background, hands-free shot, clean.'),
('mt-img-comparison',   'Comparison Table',       'image', 'image', 'Feature comparison graphic: {{product_a}} vs {{product_b}}. Clean table, {{color}} highlight, professional.'),
('mt-img-award-badge',  'Award / Badge',          'image', 'image', 'Achievement badge: {{award_name}}. Premium, {{color}}, embossed style, suitable for website.'),
('mt-img-map',          'Location / Map',         'image', 'image', 'Stylized map graphic: {{location}} with {{color}} pin. Minimal, flat, no Google branding.'),
('mt-img-stats-visual', 'Stats Visualization',    'image', 'image', 'Data stat visual: {{stat}} in bold. Supporting {{chart_type}}, {{color}} accent, clean, factual.'),
('mt-img-quote',        'Pull Quote',             'image', 'image', 'Pull quote graphic: "{{quote}}" — {{author}}. {{style}} typography, {{color}} accent, shareable.'),
('mt-img-timeline-vis', 'Timeline Visual',        'image', 'image', 'Timeline graphic: {{milestones}} key events. Horizontal, {{color}}, clean, 1200x400px.'),
('mt-img-feature-grid', 'Feature Grid',           'image', 'image', '3x2 feature grid: {{product}} features with icons. {{color}} accent, clean cards, white background.'),
('mt-img-tech-stack',   'Tech Stack Visual',      'image', 'image', 'Technology stack diagram: {{technologies}}. Clean icons, connecting lines, {{color}}, professional.'),
('mt-img-workflow',     'Workflow Diagram',        'image', 'image', 'Workflow: {{step_count}} steps for {{process}}. Arrows, {{color}} accent, minimal, clear.'),
('mt-img-security',     'Security / Trust',       'image', 'image', 'Security trust visual: {{compliance}} badges + shield. Professional, {{color}}, authoritative.'),
('mt-img-integration',  'Integration Hub',        'image', 'image', 'Integration diagram: {{central_product}} connecting {{count}} tools. Hub-spoke, {{color}}, clean.'),
('mt-img-pricing-card', 'Pricing Card',           'image', 'image', 'Pricing card graphic: {{tier}} plan at {{price}}. Highlighted, {{color}} badge, clean typography.'),
('mt-img-announcement', 'Announcement Banner',    'image', 'image', 'Product announcement: {{feature}} launch. Bold, {{color}}, excitement, social-ready, 1200x628.'),
('mt-img-404-cute',     'Friendly Error',         'image', 'image', 'Friendly error illustration: {{mascot}} looking lost. Cute, {{color}}, brand-safe, on-brand.'),
('mt-img-loading',      'Loading / Progress',     'image', 'image', 'Loading state illustration: {{context}} in progress. {{color}}, animated feel, optimistic.'),
('mt-img-confetti',     'Success / Celebration',  'image', 'image', 'Success celebration: confetti, {{color}} palette, joy, suitable for completion screen or email.');

-- Video / Seedance 2.0 (30)
INSERT OR IGNORE INTO studio_media_templates (id, name, type, category, prompt_template) VALUES
('mt-vid-demo',          'Product Demo',          'video', 'video', 'Screencast-style product demo of {{product}}. {{duration}}s, voice-over placeholder, clean UI transitions, professional.'),
('mt-vid-explainer',     'Explainer',             'video', 'video', 'Animated explainer: {{concept}} in {{duration}}s. 2D motion graphics, {{color}} palette, narration placeholder.'),
('mt-vid-testimonial',   'Testimonial',           'video', 'video', 'Customer testimonial format: speaker framing for {{role}} at {{company}}. {{duration}}s, B-roll cutaways, professional.'),
('mt-vid-tutorial',      'Tutorial / How-to',     'video', 'video', '{{duration}}s tutorial: how to {{task}} in {{product}}. Screen + annotations, step labels, clean transitions.'),
('mt-vid-social-15',     'Social Short (15s)',     'video', 'video', '15-second hook video: {{hook_concept}}. Fast cuts, text overlays, mobile-first 9:16, no sound required.'),
('mt-vid-social-30',     'Social Short (30s)',     'video', 'video', '30-second social video: {{message}}. 9:16, captions, visual hook in first 3s, CTA end card.'),
('mt-vid-hero-loop',     'Hero Loop',             'video', 'video', 'Seamless 8s hero background loop: {{visual_theme}}. Abstract, {{color}} tones, no text, web-optimized.'),
('mt-vid-feature',       'Feature Launch',        'video', 'video', '{{duration}}s feature reveal: {{feature_name}} in {{product}}. Zoom-in reveal, smooth transitions, brand colors.'),
('mt-vid-onboarding',    'Onboarding Welcome',    'video', 'video', '{{duration}}s welcome video for new {{product}} users. Friendly tone, UI walkthrough highlights, encouraging CTA.'),
('mt-vid-ad-fb',         'Facebook Ad',           'video', 'video', '15-30s Facebook ad: {{value_prop}} for {{audience}}. Hook → problem → solution → CTA, captions required.'),
('mt-vid-ad-yt',         'YouTube Pre-roll',      'video', 'video', '15s non-skippable YouTube ad: {{brand}} for {{product}}. Hook in 5s, clear value prop, CTA at end.'),
('mt-vid-case-study',    'Case Study Mini-doc',   'video', 'video', '{{duration}}s mini case study: {{client}} achieved {{result}} with {{product}}. Interview-style + data visuals.'),
('mt-vid-webinar',       'Webinar Intro',         'video', 'video', '30s webinar opening: {{topic}} hosted by {{brand}}. Professional, title card, speaker intro format.'),
('mt-vid-changelog',     'Changelog / Release',   'video', 'video', '{{duration}}s changelog video: {{version}} release highlights. Screen recordings + text callouts, upbeat.'),
('mt-vid-comparison',    'Comparison Video',      'video', 'video', '{{duration}}s: {{product}} vs {{competitor}}. Side-by-side demo, objective tone, conclusion CTA.'),
('mt-vid-countdown',     'Launch Countdown',      'video', 'video', '15s launch countdown for {{product}}. Dramatic reveal, {{color}} brand, social-optimized, 1:1 or 16:9.'),
('mt-vid-stats',         'Stats / Data Story',    'video', 'video', '{{duration}}s data story: {{key_stat}} animated. Kinetic typography, {{color}}, impactful, shareable.'),
('mt-vid-behind',        'Behind the Scenes',     'video', 'video', '{{duration}}s behind-the-scenes: {{team_or_process}}. Raw, authentic, human, casual edit style.'),
('mt-vid-interview',     'Expert Interview',      'video', 'video', '{{duration}}s interview clip: {{expert}} on {{topic}}. Talking head + B-roll, professional framing.'),
('mt-vid-howworks',      'How It Works',          'video', 'video', '{{duration}}s: how {{product}} works in 3 steps. Motion graphics, {{color}}, clear, reassuring tone.'),
('mt-vid-aissi',         'AI-assisted Screengrab','video', 'video', 'AI-enhanced screen recording: {{feature}} in {{product}}. Auto-zoom on interactions, callouts, clean.'),
('mt-vid-retargeting',   'Retargeting Ad',        'video', 'video', '15s retargeting: reminder for {{product}} visitors. Personalized feel, urgency, {{discount}} offer.'),
('mt-vid-unboxing',      'Unboxing / Setup',      'video', 'video', '{{duration}}s unboxing / first-run of {{product}}. Excitement, close-ups, ASMR-friendly pacing.'),
('mt-vid-culture',       'Team Culture',          'video', 'video', '{{duration}}s culture video: {{company}} team values. Authentic, diverse, high-energy, recruitment angle.'),
('mt-vid-annual',        'Annual Recap',          'video', 'video', '{{duration}}s year in review: {{year}} highlights for {{brand}}. Milestones, growth stats, emotional tone.'),
('mt-vid-promo',         'Promo / Sale',          'video', 'video', '15s promo: {{discount}}% off {{product}}. Urgent, bold text, countdown, CTA, 9:16 + 1:1 versions.'),
('mt-vid-tutorial-short','Quick Tip (60s)',        'video', 'video', '60-second power tip: {{tip}} in {{product}}. Fast, punchy, screen + annotations, no fluff.'),
('mt-vid-waitlist',      'Waitlist Launch',       'video', 'video', '30s waitlist teaser: {{product}} coming soon. Mystery, {{color}}, intrigue, email capture CTA.'),
('mt-vid-404',           'Error Page Loop',       'video', 'video', '6s looping animation for 404 page: {{theme}}. Subtle, {{color}}, not distracting, web-embeddable.'),
('mt-vid-loader',        'Loader Animation',      'video', 'video', '3s branded loader for {{product}}. {{color}}, smooth, memorable, optimized for web (< 200KB).');

-- HyperFrames HTML→MP4 (15)
INSERT OR IGNORE INTO studio_media_templates (id, name, type, category, prompt_template) VALUES
('mt-hf-landing',    'Animated Landing',      'hyperframe', 'hyperframe', 'Animate {{landing_url}} HTML: scroll-triggered entrance, hero fade-in, stagger features. 60fps, {{duration}}s.'),
('mt-hf-scroll',     'Scroll Story',          'hyperframe', 'hyperframe', 'Scroll-driven animation for {{section}}: parallax layers, text reveals, {{color}} highlights. Web-to-video.'),
('mt-hf-dataviz',    'Data Viz Animation',    'hyperframe', 'hyperframe', 'Animate {{chart_type}} chart: count-up numbers, bar grow, line draw. {{color}} palette, {{duration}}s, 60fps.'),
('mt-hf-product',    'Product Reveal',        'hyperframe', 'hyperframe', 'CSS product reveal: {{product}} UI emerging from dark background. {{color}} glow, 10s loop.'),
('mt-hf-comparison', 'Before/After Slide',    'hyperframe', 'hyperframe', 'Animated before/after: slider reveals {{improvement}}. Smooth, {{duration}}s, web-quality.'),
('mt-hf-pricing',    'Pricing Toggle Anim',   'hyperframe', 'hyperframe', 'Animate monthly/annual pricing toggle for {{product}}. Price morphs, {{color}} highlight, 3s clip.'),
('mt-hf-ticker',     'Stats Ticker',          'hyperframe', 'hyperframe', 'Count-up ticker: {{metrics}} animate from 0. {{color}}, dramatic pause, 8s, loop-ready.'),
('mt-hf-map',        'Map Pin Drop',          'hyperframe', 'hyperframe', 'SVG map animation: {{country_count}} locations pin-drop. {{color}} markers, sequence, {{duration}}s.'),
('mt-hf-timeline',   'Timeline Animation',    'hyperframe', 'hyperframe', 'Animated timeline: {{event_count}} milestones for {{brand}}. Horizontal scroll or vertical reveal.'),
('mt-hf-form',       'Form Fill Demo',        'hyperframe', 'hyperframe', 'Animated form completion: {{form_name}} fields fill, validate, submit. Real UI, {{duration}}s.'),
('mt-hf-dashboard',  'Dashboard Boot',        'hyperframe', 'hyperframe', 'Dashboard load animation: charts populate, KPIs count up, {{color}} accents. 8s, 60fps.'),
('mt-hf-notification','Notification Stack',   'hyperframe', 'hyperframe', 'Stacked notification toasts animate in: {{messages}}. {{color}}, stagger, dismiss, 10s.'),
('mt-hf-code',       'Code Typewriter',       'hyperframe', 'hyperframe', 'Code editor typewriter: {{code_snippet}} appears. Syntax highlight, {{color}} theme, {{duration}}s.'),
('mt-hf-logo-reveal','Logo Reveal',           'hyperframe', 'hyperframe', 'CSS logo reveal for {{brand}}: SVG draw + fill + pulse. {{color}}, 5s, export-ready.'),
('mt-hf-cta',        'CTA Pulse Loop',        'hyperframe', 'hyperframe', 'Animated CTA button: {{cta_text}} with {{color}} pulse, hover state loop. 3s, web-embeddable.');

-- Audio / Jingle (8)
INSERT OR IGNORE INTO studio_media_templates (id, name, type, category, prompt_template) VALUES
('mt-aud-brand',       'Brand Jingle',          'audio', 'audio', 'Short brand jingle for {{brand}}: {{duration}}s, {{genre}} style, {{mood}} tone, no lyrics, logo-stinger use.'),
('mt-aud-notification','Notification Sound',    'audio', 'audio', 'UI notification sound for {{product}}: {{duration}}ms, {{character}} feel, pleasant, not startling.'),
('mt-aud-success',     'Success / Completion',  'audio', 'audio', 'Success chime: {{product}} task completed. {{duration}}ms, satisfying, positive, subtle.'),
('mt-aud-error',       'Error / Alert',         'audio', 'audio', 'Error alert sound: {{severity}} level, {{duration}}ms, attention-grabbing without being harsh.'),
('mt-aud-intro',       'Podcast / Video Intro', 'audio', 'audio', '{{duration}}s intro music for {{show_name}}: {{genre}}, {{mood}}, energetic open, fades to background.'),
('mt-aud-bg-loop',     'Background Loop',       'audio', 'audio', '{{duration}}s background music loop for {{context}}: {{genre}}, {{mood}}, no melody clash, web-friendly.'),
('mt-aud-transition',  'Scene Transition',      'audio', 'audio', 'Transition sound: {{duration}}ms swoosh/whoosh for {{product}} UI or video. {{character}}, clean.'),
('mt-aud-cta',         'CTA Stinger',           'audio', 'audio', '{{duration}}ms CTA stinger for {{brand}} ad: impactful, {{mood}}, punctuates call-to-action moment.');
